/*
 * Copyright (C) 2017-18 by TS Sundquist
 * 
 * All rights reserved.
 * 
 */

package sog.util;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;
import java.util.stream.Collectors;

import sog.core.App;
import sog.core.Assert;
import sog.core.Strings;
import sog.core.Test;

/**
 * For delivery of error messages.
 * 
 * Faults are associated with a source object. The default, when no source is given, is to identify
 * the fault with a global application object. Clients can register to listen for global
 * application faults, or for faults associated with a particular source.
 * 
 * The Fault instance encapsulates diagnostic information about the defect as a list of String
 * detail messages, and also holds a String encoding of the stack trace where the Fault was generated. 
 * The implementation of Printable presents the diagnostic information.
 */
public class Fault implements Printable {
	
	
	/* 
	 * An object to serve as the source for global application faults. We could use the App singleton
	 * but this might introduce an unwanted circular dependency Fault -> App -> Fatal -> Fault
	 * that could lead to class initialization issues.
	 * */
	private static final Object APP = new Object() {};
	
	/*
	 * The key is the associated source object, or APP if none was given. The value is
	 * the associated set of fault-consumers (listeners) that have registered to be notified
	 * for faults generated by the source.
	 */
	private static final Map<Object, Set<Consumer<Fault>>> SOURCE_TO_LISTENERS = new HashMap<>();

	/**
	 * Register the given listener to receive notification of faults associated with the given source.
	 * 
	 * @param listener
	 */
	@Test.Decl( "Throws AssertionError for null source" )
	@Test.Decl( "Throws AssertionError for null listener" )
	@Test.Decl( "Subsequent faults for given source are deleivered to listener" )
	@Test.Decl( "Subsequent faults for other sources are ignored" )
	public static void addListener( Object source, Consumer<Fault> listener ) {
		Assert.nonNull( source );
		Assert.nonNull( listener );
		
		Set<Consumer<Fault>> listenerSet = Fault.SOURCE_TO_LISTENERS.get( source );
		if ( listenerSet == null ) {
			listenerSet = new HashSet<Consumer<Fault>>();
			Fault.SOURCE_TO_LISTENERS.put( source, listenerSet );
		}
		listenerSet.add( listener );
	}
	
	/**
	 * Register the given listener to receive notification of GLOBAL application faults.
	 * 
	 * @param listener
	 */
	@Test.Decl( "Throws AssertionError for null listener" )
	@Test.Decl( "Subsequent faults for GLOBAL application are deleivered to listener" )
	@Test.Decl( "Subsequent faults for other sources are ignored" )
	public static void addListener( Consumer<Fault> listener ) {
		Fault.addListener( Fault.APP, Assert.nonNull( listener ) );
	}
	
	/**
	 * Unsubscribe the given listener waiting on faults associated with the given source.
	 * 
	 * @param listener
	 */
	@Test.Decl( "Throws AssertionError for null source" )
	@Test.Decl( "Throws AssertionError for null listener" )
	@Test.Decl( "Subsequent faults for given source are not deleivered to listener" )
	public static void removeListener( Object source, Consumer<Fault> listener ) {
		Assert.nonNull( source );
		Assert.nonNull( listener );
		
		Set<Consumer<Fault>> listenerSet = Fault.SOURCE_TO_LISTENERS.get( source );
		if ( listenerSet != null ) {
			listenerSet.remove( listener );
		}
	}

	/**
	 * Unsubscribe the given listener waiting on faults associated with the GLOBAL application.
	 * 
	 * @param listener
	 */
	@Test.Decl( "Throws AssertionError for null listener" )
	@Test.Decl( "Subsequent faults for GLOBAL application are not deleivered to listener" )
	public static void removeListener( Consumer<Fault> listener ) {
		Fault.removeListener( Fault.APP, Assert.nonNull( listener ) );
	}


	
	
	/* The object associated with the source of the Fault. Listeners for this object will be notified. */
	private final Object source;
	
	/* Description of the nature of the defect. */
	private final String description;
	
	/* Optional list of detail messages. */
	private final List<String> details;
	
	/* String encoding of the stack trace from the point where the Fault was generated. */
	private final List<String> faultLocation;
	
	/**
	 * Construct a {@code Fault} representing an application defect associated with the given source object.
	 * 
	 * The required non-empty description explains the nature of the fault. The optional
	 * detail objects provide additional context.
	 * 
	 * @param source
	 * @param description
	 * @param details
	 */
	@Test.Decl( "Throws AssertionError for null source" )
	@Test.Decl( "Throws AssertionError for enpty description" )
	@Test.Decl( "Given details are included in print" )
	@Test.Decl( "Fault location is included in print" )
	public Fault( Object source, String description, Object ... details ) {
		this.source = Assert.nonNull( source );
		this.description = Assert.nonEmpty( description );
		this.details = Arrays.stream( details ).map( Strings::toString )
			.collect( Collectors.toCollection( ArrayList<String>::new ) );
		this.faultLocation = App.get().getLocation().collect( Collectors.toList() );
	}

	/**
	 * Construct a {@code Fault} representing an application defect associated with the GLOBAL application.
	 * 
	 * The required non-empty description explains the nature of the fault. The optional
	 * detail objects provide additional context.
	 * 
	 * @param description
	 * @param details
	 */
	@Test.Decl( "Throws AssertionError for empty description" )
	@Test.Decl( "Given details are included in print" )
	@Test.Decl( "Fault location is included in print" )
	public Fault( String description, Object ... details ) {
		this( Fault.APP, description, details );
	}

	
	/**
	 * Broadcasts a {@code Fault} to all registered listeners.
	 * 
	 * Similar to throwing an exception but "gentler". Useful in compilation-style
	 * processes where it's useful to gather as much feedback as possible.
	 */
	@Test.Decl( "Fault is delivered to each registered listener" )
	@Test.Decl( "Listeners registered for other sources are ignored" )
	public void toss() {
		Set<Consumer<Fault>> listeners = Fault.SOURCE_TO_LISTENERS.get( this.source );
		if ( listeners != null ) {
			listeners.forEach( this::deliver );
		}
	}

	/**
	 * Notify the indicated listener.
	 * 
	 * @param listener
	 */
	@Test.Decl( "Throws AssertionError for null listener" )
	@Test.Decl( "Fault is delivered to given listener" )
	@Test.Decl( "All other listeners are ignored" )
	public void deliver( Consumer<Fault> listener ) {
		Assert.nonNull( listener ).accept( this );
	}
	

	/**
	 * Add an additional detail to this {@code Fault}.
	 * Mutator pattern allows chaining.
	 * 
	 * @param detail
	 * @return
	 */
	@Test.Decl( "Throws AssertionError for null detail" )
	@Test.Decl( "Detail converted using Strings.toString()" )
	@Test.Decl( "Detail is appended to previous details" )
	@Test.Decl( "Return is this Fault instance" )
	public Fault addSource( Object detail ) {			
		this.details.add( Strings.toString( detail ) );
		return this;
	}
	
	
	/**
	 * Description of the fault
	 */
	@Override
	@Test.Decl( "Returns non-empty description" )
	public String toString() {
		return "Fault(" + this.description + ")";
	}
	

	/**
	 * Write a "pretty-print" representation on the given writer
	 * 
	 * @see sog.util.Printable#print(sog.util.IndentWriter)
	 */
	@Override
	@Test.Decl( "Throws AssertionError for null writer" )
	@Test.Decl( "Description printed" )
	@Test.Decl( "Fault location printed" )
	@Test.Decl( "All provided details printed" )
	public void print( IndentWriter out ) {
		out.println( this.toString() );
		out.increaseIndent();

		out.println( "LOCATION:" );
		out.increaseIndent();
		this.faultLocation.forEach( out::println );
		out.decreaseIndent();

		out.println( "SOURCE(S):" );
		out.increaseIndent();
		this.details.forEach( out::println );
		out.decreaseIndent();

		out.decreaseIndent();
		out.println("");
	}

	
}
